### ISSUE TITLE
Original Time Series Data

### ISSUE THREAD

**Issue by jacobf18** [lucapton/ICLabel-Dataset#2]
Is the original time series data in the ICLabel dataset as well?  If not, is there a place I could access it?

**Comment by adam2392** [comment]
Hi @lucapton just wanted to follow up on this? Thank you!

**Comment by lucapton** [comment]
The original time series are not available. All that is provided is included in this repository as is. I realize having the original time series would make this dataset much more versatile, but unfortunately that's not possible.
